# Generated by Django 4.1.6 on 2023-02-08 07:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=None, max_length=100, verbose_name='Number')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('pax_capacity', models.IntegerField(default=None, verbose_name='PAX Capacity')),
                ('vehicle_capacity', models.IntegerField(default=None, verbose_name='Vehicle Capacity')),
                ('pet_capacity', models.IntegerField(default=None, verbose_name='Pet Capacity')),
                ('hire_type', models.CharField(choices=[('Hire', 'Hire'), ('Charter', 'Charter')], default=None, max_length=100, verbose_name='Hire/Charter')),
                ('lower_deck_seat', models.IntegerField(default=None, verbose_name='Lower Deck Seat')),
                ('upper_deck_seat', models.IntegerField(default=None, verbose_name='Upper Deck Seat')),
                ('commission', models.IntegerField(default=None, null=True, verbose_name='Commission %')),
                ('flat_rate', models.IntegerField(blank=True, default=None, null=True, verbose_name='Flat Rate')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
            ],
            options={
                'verbose_name': 'Boat',
                'verbose_name_plural': 'Boats',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_product', models.CharField(max_length=100)),
                ('order_amount', models.CharField(max_length=25)),
                ('order_payment_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='', max_length=100, verbose_name="Port's City Name")),
                ('port_name', models.CharField(default=None, max_length=100, verbose_name="Port's Name")),
                ('location_url', models.CharField(default=None, max_length=100, verbose_name="Port's Location URL")),
                ('port_type', models.CharField(choices=[('OD pair', 'OD pair'), ('OO pair', 'OO pair')], default=None, max_length=100, verbose_name="Port's Type")),
                ('pet_allowed', models.BooleanField(default=1, verbose_name='Pets Allowed')),
                ('vehicle_allowed', models.BooleanField(default=1, verbose_name='Vehicle Allowed')),
                ('contact_name', models.CharField(default=None, max_length=100, verbose_name="Port's Contact Person")),
                ('contact_number', models.CharField(default=None, max_length=100, verbose_name="Port's Contact Number")),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=None, verbose_name='Journey Duration in Minutes')),
                ('lower_deck_fare', models.IntegerField(default=None, verbose_name='Lower Deck Fare')),
                ('upper_deck_fare', models.IntegerField(blank=True, default=None, null=True, verbose_name='upper Deck Fare')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='ticket_admin.port')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=100, verbose_name='Vehicle Type')),
                ('model', models.CharField(default=None, max_length=100, verbose_name='Vehicle Model')),
                ('price', models.CharField(default=None, max_length=100, verbose_name='Vehicle Price')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
            },
        ),
        migrations.CreateModel(
            name='ValueAddedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name='Name')),
                ('type', models.CharField(default=None, max_length=100, verbose_name='Type')),
                ('price', models.CharField(default=None, max_length=100, verbose_name='Price')),
                ('gst_rate', models.CharField(default=None, max_length=100, verbose_name='GST % applicable')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Value Added Service',
                'verbose_name_plural': 'Value Added Services',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(default=datetime.datetime.now, verbose_name='Departure Date')),
                ('departure_time', models.TimeField(default=datetime.datetime.now, verbose_name='Departure Time')),
                ('pet_booked', models.IntegerField(blank=True, default=0, verbose_name='Pet Slots Booked')),
                ('vehicle_booked', models.IntegerField(blank=True, default=0, verbose_name='Vehicle Slots Booked')),
                ('seat_booked_lower', models.IntegerField(blank=True, default=0, verbose_name='Lower Deck Booked Sets')),
                ('seat_booked_upper', models.IntegerField(blank=True, default=0, verbose_name='upper Deck Booked Sets')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('boat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='boat_id', to='ticket_admin.boat')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='route_id', to='ticket_admin.route')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='RouteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name="Boat's Type")),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route Return Type Master',
                'verbose_name_plural': 'Route Return Type Master',
            },
        ),
        migrations.AddField(
            model_name='route',
            name='route_return',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Route_Return_Type', to='ticket_admin.routetype'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='source', to='ticket_admin.port'),
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=100, verbose_name='Pet Type')),
                ('weight', models.CharField(default=None, max_length=100, verbose_name='Pet Weight')),
                ('price', models.CharField(default=None, max_length=100, verbose_name='Pet Price')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pet Type',
                'verbose_name_plural': 'Pet Types',
            },
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=None, verbose_name='Validity Days')),
                ('trip', models.IntegerField(default=None, verbose_name='Trips count')),
                ('price', models.IntegerField(default=None, verbose_name='Pass Price')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='pass_route_id', to='ticket_admin.route')),
            ],
            options={
                'verbose_name': 'Pass Info',
                'verbose_name_plural': 'Passes Info',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=100, verbose_name='Parcel Type')),
                ('weight', models.CharField(default=None, max_length=100, verbose_name='Parcel Weight')),
                ('price', models.CharField(default=None, max_length=100, verbose_name='Parcel Price')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcel Type',
                'verbose_name_plural': 'Parcel Types',
            },
        ),
        migrations.CreateModel(
            name='BoatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name="Boat's Type")),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boat Type Master',
                'verbose_name_plural': 'Boats Type Master',
            },
        ),
        migrations.CreateModel(
            name='BoatOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default=None, max_length=100, verbose_name="Company's name")),
                ('sub_company_name', models.CharField(default=None, max_length=100, verbose_name="Sub-Company's name")),
                ('owner_name', models.CharField(default=None, max_length=100, verbose_name="owneer's name")),
                ('company_address', models.TextField(default=None, verbose_name='Address')),
                ('company_mobile', models.CharField(default=None, max_length=100, verbose_name='Mobile Number')),
                ('company_email', models.EmailField(default=None, max_length=100, verbose_name='Mobile E-mail')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boat Owner',
                'verbose_name_plural': 'Boat Owners',
            },
        ),
        migrations.CreateModel(
            name='BoatCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, verbose_name="Boat's Category")),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('status', models.BooleanField(default=1, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boat Category Master',
                'verbose_name_plural': 'Boat Categories Master',
            },
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_admin.boatcategory'),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_admin.boatowner'),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticket_admin.boattype'),
        ),
        migrations.AddField(
            model_name='boat',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
