# Generated by Django 4.1.6 on 2023-02-16 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='ticket_admin.port'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='ticket_admin.port'),
        ),
    ]
