# Generated by Django 4.1.6 on 2023-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_admin', '0004_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='test',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='tset',
            field=models.DurationField(default=None),
        ),
    ]
